import './globals.css';
import type { Metadata } from 'next';
import { Provider } from 'react-redux';
import store from '@/Redux/store';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
