import ReduxProvider from '@/components/ReduxProvider';
import './globals.css';
import type { Metadata } from 'next';
// Adjust path if needed

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
          <ReduxProvider> 
            {children}
          </ReduxProvider>
        
        
      </body>
    </html>
  );
}
