import ReduxProvider from '@/components/ReduxProvider';
import './globals.css';
import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/themePerovider';
// Adjust path if needed

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden bg-white text-black ">
          <ReduxProvider> 
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
            </ThemeProvider>
          </ReduxProvider>
        
        
      </body>
    </html>
  );
}
