import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/themePerovider';
import QueryProvider from '../(providers)/QueryProvider';


export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};


export default function DashboardRoot({children,} : {children : React.ReactNode}){
    
    return (
        <>
        <ThemeProvider attribute="class"  enableSystem>
          <QueryProvider>
          {children}
          </QueryProvider>   
        </ThemeProvider>
        </>
    )
}